### ISSUE TITLE
Instruction coverage

### ISSUE THREAD

**Issue by agrobman** [google/riscv-dv#131]
Do you have any plans to add coverage to the generator to collect various instructions properties, generated. For ex, types, branch offsets, L/S offsets , reg operands etc?

**Comment by taoliug** [comment]
Yes, it's one of the important features we are working on. Expect to be ready in around a month time.

**Comment by taoliug** [comment]
The flow is checked in, please take a look.
There will be more covergroup added later, but the most common ones are ready.

**Comment by taoliug** [comment]
BTW, I have added the coverage options for incisive
You can refer to how it's done for vcs
https://github.com/google/riscv-dv/blob/master/yaml/simulator.yaml#L25
