### ISSUE TITLE
scripts/spike_log_to_trace_csv.py rv32 log file is deleted before conversion

### ISSUE THREAD

**Issue by sdexter-numa** [google/riscv-dv#178]
I'm having a problem with this script. Last working version was git SHA 80d4294. It seems that the first 'sed' command deletes the entire log file, and after that there are no instructions to convert. I see this also happening with the latest https://github.com/lowRISC/ibex, at git SHA 1e8381b. Every comparison fails because the log files from Spike are empty after this script runs on them.

**Comment by taoliug** [comment]
Thanks for reporting, this should be fixed now. We will merge this change to ibex repo later today.
