### ISSUE TITLE
Spike version to run run.py

### ISSUE THREAD

**Issue by abdullahyildiz** [google/riscv-dv#207]
There is an update in how Spike handles commit logs. Could you please check the following issue at riscv-isa-sim:

https://github.com/riscv/riscv-isa-sim/issues/342#issue-502486021

**Comment by taoliug** [comment]
Need to add this new option here
https://github.com/google/riscv-dv/blob/master/yaml/iss.yaml#L18
However, this change is not backward compatible, it's going to cause issue for people use older spike version.

**Comment by abdullahyildiz** [comment]
@taoliug,
You are right. I just wanted to let you know about this issue.
