### ISSUE TITLE
Questionable start code for CSR test - why jump to csr_fail 32 times?

### ISSUE THREAD

**Issue by sdexter-numa** [google/riscv-dv#222]
https://github.com/google/riscv-dv/blob/1c55c114226c6ff3cdfcd9371763403bb36293d9/scripts/gen_csr_test.py#L203-L217

This code results in the following start code:
`.macro init`
`.endm`
`.section .text.init`
`.globl _start`
`.option norvc`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`j csr_fail`
`_start:`
`        # misa`

What's the purpose of these 32 calls to "csr_fail" at the beginning of the test?

**Comment by udinator** [comment]
Hi @sdexter-numa - I had initially added this to account for the boot address offset of the core I am testing, but it is actually not necessary at all, submitted a PR to remove this entirely.
Thanks for pointing this out!
