### ISSUE TITLE
Usage of --target_dir or --core_setting_dir 

### ISSUE THREAD

**Issue by eroom1966** [google/riscv-dv#237]
@taoliug 
There is a setting directory and a target directory, 
could you please clarify how to configure the generator for different isa selections ?

Also, how do I overlay target/<isa>/* with my configured core outside of the riscv-dv tree
do we need to use --target_dir and remove --core_setting_dir ?

**Comment by taoliug** [comment]
For now, --target will use the predefined setting to override other configurations. 
If you want to use your own setting, please use --core_setting_dir to specify the directory of your setting directory.
