### ISSUE TITLE
adding simulator commands to cov.py

### ISSUE THREAD

**Issue by simond-imperas** [google/riscv-dv#292]
Hi Tao
I want to add sim commands to underlying rtl sim used for coverage, eg +UVM_VERBOSITY=UVM_HIGH
eg to the run.py simulator runs undereath cov.py
how do I do this - do we need to add a new cov.py --sim_opts "+UVM_VERBOSITY=UVM_HIGH"
thanks
Simon

**Comment by taoliug** [comment]
This is now fixed. When running with -v, UVM_VERBOSITY will be set to UVM_HIGH automatically.
