### ISSUE TITLE
Enhance passing argument for function

### ISSUE THREAD

**Issue by danghai** [google/riscv-dv#373]
It seems the number of arguments for each function become larger. Ex:
```
    gen(matched_list, args.csr_yaml, args.end_signature_addr, args.isa,
        args.simulator, args.simulator_yaml, output_dir, args.so,
        args.co, args.lsf_cmd, args.seed, cwd, args.cmp_opts,
        args.sim_opts, args.gen_timeout, args.core_setting_dir,
        args.user_extension_dir, args.cov, args.log_suffix, args.batch_size,
        args.seed_yaml, args.verbose, args.exp)
```
I have one idea that we should only pass one configuration argument (It may be dictionary data structure) that contains all configuration from the command line. For example:
```
   gen(matched_list, args)
```
args has keys, and values corresponding. So, we are not worry about order, and number arguments for calling it every time. Furthermore, all configuration takes place one place (ex: load_config), so it is easy to add, remove, and maintain it. Do you think is it a good idea to implement it?

**Comment by taoliug** [comment]
I think it's a good idea to change the gen function, as it's unlikely to be called by other python program outside run.py. We could to the same thing for collect_cov function in cov.py. For other functions with less input arguments, we can keep them unchanged.
