### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by danghai** [google/riscv-dv#418]
The project riscv-dv should have a python package? And then, it can be public on PyPI for easier download by pip?

**Comment by taoliug** [comment]
taliu@taliu0:~/riscv-dv$ pip3 install -e .
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from riscv-dv==1.0) (5.1.2)
Requirement already satisfied: bitstring in ~/.local/lib/python3.7/site-packages (from riscv-dv==1.0) (3.1.6)
Installing collected packages: riscv-dv
  Found existing installation: riscv-dv 1.0
    Uninstalling riscv-dv-1.0:
      Successfully uninstalled riscv-dv-1.0
  Running setup.py develop for riscv-dv
Successfully installed riscv-dv
taliu@taliu0:~/riscv-dv$ run
**bash: run: command not found**

Seems like i cannot run it, PTAL.

**Comment by danghai** [comment]
Could you try `pip3 install --user git+https://github.com/google/riscv-dv.git`?

**Comment by danghai** [comment]
It works for me for both ways. Could you clean/remove your directory, and re-try it?

**Comment by taoliug** [comment]
It shows the installation is successful, but no local run/cov executable is created under riscv-dv

**Comment by danghai** [comment]
Could you try uninstall, and then reinstall again:
```
pip3 uninstall -y riscv-dv
pip3 install --user -e .
```

For me it shows:
```
danghai@ubuntu:~/hhoangda/riscv-dv$ which cov
/home/danghai/.local/bin/cov
```

**Comment by taoliug** [comment]
I can see it's installed under ~/.local/bin, but the ~/.local/bin is not in the $PATH environment variable, so it cannot be found automatically.

**Comment by taoliug** [comment]
Solved the problem by adding ~/.local/bin to the local variable. Maybe we need to mention this in the README, it might be a common problem for ubuntu
https://askubuntu.com/questions/799302/ubuntu-cant-find-an-executable-file-in-local-bin

**Comment by danghai** [comment]
Cool! I will mention it. You can run it outside the `riscv-dv` directory that you cloned? I mean you can run it anywhere without the hardware source? I put all files into MANIFEST. But I cannot find the location of package.

**Comment by taoliug** [comment]
One problem is that if I have multiple clones, how can I run for each clone? Should the python package be put under riscv-dv directory?

**Comment by taoliug** [comment]
I think this might be OK, as I can always run with "python3 xxx/xxx/run.py ..."

**Comment by danghai** [comment]
For multiple clones, you should re-install it by `pip3 install --user -e .` for each clone.

**Comment by taoliug** [comment]
What if I want to work on two clones in parallel? I believe there will just be one copy of package under .local/bin?

**Comment by danghai** [comment]
For this situation, I think you should use a virtual environment. For example:
```
virtualenv ~/riscv-venv/
source ~/riscv-venv/bin/activate
pip install --user -e .
```
And deactive when you done: `deactivate`.
it keeps all its dependencies in a separate Python environment.

**Comment by taoliug** [comment]
I think it's more complicated than the current use model. In many cases, I may have multiple local clones working on different things. We should recommend user to use the below approach in this scenario.

python3 <path1>/run.py ....
python3 <path2>/run.py ....

I am also a bit worry about the naming conflict. "run" seems to be too general which could collide with other executables. Anyway, the new use model does make things easier in many cases, but we should clarify the scenarios that the old use model is recommended.

**Comment by taoliug** [comment]
I think for developers which may work on multiple clones in parallel, we should recommend to use the old flow. For normal users which just has one clone, the python package approach is recommended.

**Comment by danghai** [comment]
Okay I will mention it. All examples use the old flow, or python package?

**Comment by taoliug** [comment]
I think using python package is fine, just have a separate section to call out the use model for the developers.
