### ISSUE TITLE
Publishing riscv-dv to PyPI

### ISSUE THREAD

**Issue by danghai** [google/riscv-dv#432]
Hi @taoliug , could you publish riscv-dv to PyPI?. I register this project under  `riscv_dv_dev@google.com`. You can read information about how to public here:
https://realpython.com/pypi-publish-python-package/
(Look for `publishing to PyPI`). After publishing, I think user can install by: `pip3 install riscv-dv`. It includes all hardware, and script source code in `site-package`.

**Comment by taoliug** [comment]
Will address it in the next couple of days.

**Comment by taoliug** [comment]
Closing some stale bug
