### ISSUE TITLE
Implement storing the commands that would be executed as a script in a specific file, but do not execute them.

### ISSUE THREAD

**Issue by danghai** [google/riscv-dv#437]
I think it is a good idea to implement a switch (ex --debug/-d cmd.log) that store the commands that would be executed in a specific file, but do not execute them. It helps you enhance debug. For example,
1. I use `qrun` tool, but I do not have `vcs` tool. I can run --debug switch. I can get all command lines of all steps for vcs tool without errors.
2. It will collect all internal, and external options from YAML. Ex, you have `gcc_opts` in yaml, or you have `gcc_opts` on command line, you can run this switch to check these gcc options already are passed on command line without running a real test (from compile, simulate, ...).
3. Someone gets error, you can ask them to run this switch, and provide the command log file. From there, you can check options are passed correct or not.
...

**Comment by taoliug** [comment]
I think this is done now. Thanks for the contribution
