### ISSUE TITLE
doc pdf file is not in repo

### ISSUE THREAD

**Issue by simon5656** [google/riscv-dv#456]
I thought the pdf of the docs would be auto generated and placed in the repo - but I cant find it?

**Comment by taoliug** [comment]
I have removed the PDF version because the generated doc style doesn't look very good. Please use this HTML version instead:
https://htmlpreview.github.io/?https://github.com/google/riscv-dv/blob/master/docs/build/singlehtml/index.html#document-index

**Comment by simon5656** [comment]
perfect - thanks
