### ISSUE TITLE
option: use sp register only for stack pointer and/or not use t0-t6 as targets in inst sequences

### ISSUE THREAD

**Issue by agrobman** [google/riscv-dv#463]
add plus arg option to use  only 'sp' register as a stack pointer.
Or not to use temp regs as target regs in instructions sequences.

We have interrupt handlers using temps ( t0 -t6) or use sp to save/restore them in handlers

**Comment by taoliug** [comment]
This is now fixed, please add +fix_sp=1 in your testlist.
