### ISSUE TITLE
docs, please include pre-built document in the repository

### ISSUE THREAD

**Issue by agrobman** [google/riscv-dv#468]
make requires some tools I don't have

**Comment by taoliug** [comment]
can you try "pip3 install -r requirements.txt" ?

**Comment by agrobman** [comment]
I’m not allowed to install  any SW on engineering compute network ..

**Comment by taoliug** [comment]
The prebuild document is under docs/build/singlehtml/

**Comment by agrobman** [comment]
Pop it to the docs directory or update README, please.

**Comment by taoliug** [comment]
The link is provided in the README, I will add some information about how to find it locally.
https://github.com/google/riscv-dv#document
