### ISSUE TITLE
Support to pass seed into gen_csr_test

### ISSUE THREAD

**Issue by abhijithcd** [google/riscv-dv#492]
Hi, the CSR test currently doesn't have support to take a seed to regenerate the same assembly code.
Could you please let me know if this is intended for some reason? Could the support be added?

Thank you.

**Comment by udinator** [comment]
@abhijithcd - Thanks for bringing up this issue. I can definitely add support to pass in a seed to the CSR test.

**Comment by udinator** [comment]
@abhijithcd, I have added support for this feature in #494, I will close this issue for now. Feel free to reopen this issue or open a new issue with any other questions.
