### ISSUE TITLE
Vector instructions weight

### ISSUE THREAD

**Issue by Sustrak** [google/riscv-dv#499]
Hi,
is there a way to set the weight of the vector instructions in the generator ?

Thanks.

**Comment by taoliug** [comment]
You mean increase the weight of overall vector instructions compared with other instructions, or fine grained weight control of each vector instruction.  It's not supported yet, but I could add some knob to control the weight of each ISA extension group.

**Comment by Sustrak** [comment]
I was meaning the first thing you mentioned, a knob to control the weight of each ISA extension group.

Thanks
