### ISSUE TITLE
Support Bit-manipulation extension

### ISSUE THREAD

**Issue by taoliug** [google/riscv-dv#520]
File this bug to track the progress of Bit-manipulation extension support. 
Thanks for the contribution from Mellanox, we have got the basic Bit-manipulation instruction class ready (#518). Following work:
- Create a target for B-extension
- Add tests for B-extensions. 
- [Get ovpsim setup and pass ISS sim.](https://github.com/riscv/riscv-bitmanip#imperas-riscvovpsim-reference-simulation)
- Update document
- Add functional coverage model for B-extension

Please leave your comment here if you have suggestion or feature request on B-extension testing.

**Comment by taoliug** [comment]
A rv32imcb target is created, OVPsim setting is also updated.

**Comment by taoliug** [comment]
I believe below steps are done already.

- Create a target for B-extension
- Add tests for B-extensions.
- Get ovpsim setup and pass ISS sim.

**Comment by weicaiyang** [comment]
> I believe below steps are done already.
> 
> * Create a target for B-extension
> * Add tests for B-extensions.
> * Get ovpsim setup and pass ISS sim.

Yes, these are done.

**Comment by taoliug** [comment]
Add one item: Enable spike & ovpsim co-simulation flow for B-extension.
When you update the document, please provide the links for the required toolchain

**Comment by taoliug** [comment]
Closing this bug as all required work is done. Thanks Weicai!
