### ISSUE TITLE
Vector Widening and Narrowing instructions when 2*SEW > ELEN

### ISSUE THREAD

**Issue by Sustrak** [google/riscv-dv#561]
As the RISC-V specs says

For widening:

> The destination vector register group results are arranged as if both SEW and LMUL were at twice their current settings (i.e., the destination element width is 2*SEW, and the destination vector register group LMUL is 2*LMUL).

> For all widening instructions, the destination element width must be a supported element width and the destination LMUL value must also be a supported LMUL.

For narrowing

> If (2*LMUL > 8), or (2 * SEW) > ELEN, an illegal instruction exception is raised.

The generator should check the parameter ELEN defined in the target configuration in order to generate or not widening and narrowing instructions when the SEW, configured by the `vsetvli` instruction, won't allow this instructions to be valid.

**Comment by taoliug** [comment]
We are working on updating the narrowing/widening instruction support, expect to push to upstream in a few days.

**Comment by taoliug** [comment]
This should be solved by https://github.com/google/riscv-dv/pull/598. Please reopen the issue if you see this problem.
