### ISSUE TITLE
run script doesn't fail if OVPSim executable not found

### ISSUE THREAD

**Issue by tudortimi** [google/riscv-dv#565]
I didn't set up my environment to properly point to OVPSim. The run script didn't fail, but simply complained that the OVPSim log didn't contain any instructions. 

I did some print debugging and narrowed it down to the following line.

https://github.com/google/riscv-dv/blob/150a7668b31d16eb2d8e1442c10852ec853a546f/run.py#L576

Is the return code not checked because OVPSim uses non-zero return codes even in regular operation?

**Comment by taoliug** [comment]
yes, I do remember an issue like you mentioned, but i cannot reproduce it with the latest ovpsim version. Will add the return code check back.
