### ISSUE TITLE
Add support for Xcelium

### ISSUE THREAD

**Issue by tudortimi** [google/riscv-dv#578]
Would you be interested in a PR adding support for Cadence Xcelium?

My long term goal is to run Ibex in Xcelium. They aren't happy with running it in IUS compatibility mode: https://github.com/lowRISC/ibex/pull/877 which would already work with the current riscv-dv.

Adding support for "true" Xcelium to Ibex requires adding that support here. I want to ask first before I do it to avoid something like "Xcelium isn't supported in riscv-dv" or "just use `ius` as a simulator and it will work in Xcelium too.

**Comment by taoliug** [comment]
sgtm, please go ahead to add Xcelium support

**Comment by tudortimi** [comment]
Implemented in #579
