### ISSUE TITLE
GPR results not found

### ISSUE THREAD

**Issue by jiangxuanfeng** [google/riscv-dv#634]
command: python3 run.py --iss spike
When this command is executed, there are no GPR results in the log and CSV files.Why?

**Comment by taoliug** [comment]
Can you copy the screen log here? most likely some early steps went wrong.

**Comment by taoliug** [comment]
BTW, please do sync to the latest and try, there was some bugs introduced a couple of days ago.

**Comment by jiangxuanfeng** [comment]
There are no errors in the operation, but there are only two lines in the VCs file,
pc,instr,gpr,csr,binary,mode,instr_str,operand,pad
ffffffff80000158,,,,00000073,,ecall,,

**Comment by udinator** [comment]
Hi @jiangxuanfeng can you sync to top of tree and see if this issue occurs again?

**Comment by udinator** [comment]
@jiangxuanfeng I will close this issue as it has almost been a month since the last comment in the thread.
Please feel free to open another issue (or reopen this one) if this issue still comes up.
