### ISSUE TITLE
spike version (--log-commits does not support)

### ISSUE THREAD

**Issue by jiangxuanfeng** [google/riscv-dv#635]
command: SPIKE_PATH/spike --log-commits --isa=rv32imc -l <elf>
When I run, spike does not support the -- log commit. Is my spike version too old?

**Comment by Sustrak** [comment]
When compiling spike at the step you do the `./configure` you have to pass the following parameter `--enable-commitlog`

**Comment by taoliug** [comment]
I believe Sustra's answer addressed the issue, closing it now
