### ISSUE TITLE
Run directed assembly/C tests

### ISSUE THREAD

**Issue by jiangxuanfeng** [google/riscv-dv#640]
command: python3 run.py --asm_tests ./asm_test/riscv_test.S
The result of executing this command is to generate the .Bin and .O files.
But I also want to perform simulations and comparisons. Only in this way can we have the significance of verification.
Do you have this function? How to do it?

**Comment by udinator** [comment]
Hi @jiangxuanfeng, this riscv-dv repository is only for generating random assembly files and then compiling them and producing ISS simulation logs.
To add RTL simulation and post-comparison checking of RTL trace logs, you'll have to integrate those steps yourself into this flow.
The Ibex core developed by lowRISC is a good reference model, which you can find here: https://github.com/lowRISC/ibex/tree/master/dv/uvm/core_ibex.
The Makefile here controls the whole flow, from running the instruction generator to running RTL sims to final comparison checks - it also uses a YAML based flow which can be seen at https://github.com/lowRISC/ibex/tree/master/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml.
You'll likely need a simulation script from the RTL side, you can use the sim.py script that Ibex has as a reference.
