### ISSUE TITLE
Error: how I can run the test from pygen_src?

### ISSUE THREAD

**Issue by danghai** [google/riscv-dv#655]
Hi, I got the error when I try to run the `riscv_instr_base_test.py` 
```
Traceback (most recent call last):
  File "test/riscv_instr_base_test.py", line 16, in <module>
    from pygen_src.riscv_instr_gen_config import cfg  # NOQA
ModuleNotFoundError: No module named 'pygen_src'
```

Do I miss anything to run it? Thank you

**Comment by aneels3** [comment]
Hi @danghai 
For running **riscv_instr_base_test.py**, you need to run it from **test** directory.
The dependencies are already added in **requirement.txt**
Try installing the dependencies and run it from the test directory.

-Anil

**Comment by danghai** [comment]
Hi @aneels3 . It works for me now. Thanks
