### ISSUE TITLE
Log Compare in Co-Simulation Flow

### ISSUE THREAD

**Issue by berkkis** [google/riscv-dv#67]
Hi,
Regarding the log comparison could you please elaborate on how you verify rtl instruction trace ?
Thank you.

**Comment by taoliug** [comment]
In case your processor has a tracer, you can refer to ibex TB for example
Compare script: https://github.com/lowRISC/ibex/blob/master/dv/uvm/sim.py#L193
Convert RTL trace to standard trace CSV: https://github.com/lowRISC/ibex/blob/master/dv/uvm/riscv_dv_extension/ibex_log_to_trace_csv.py
Doc: https://github.com/lowRISC/ibex/blob/master/doc/verification.rst

If there's no tracer,  the recommended approach is to monitor the register file update and compare with ISS trace. We will have an example for this published later.

**Comment by berkkis** [comment]
Thank you for the answer.
