### ISSUE TITLE
 the coverage about the special values of  floating point insruction are lower

### ISSUE THREAD

**Issue by yinhanquan** [google/riscv-dv#692]
We generated the random instructions for target rv64g,but the coverage about the special values of  floating point insruction are overall lower;especially the sfp_special_values_on_fd_value and dfp_sepcial_values_on_fd_value.

**Comment by weicaiyang** [comment]
@yinhanquan 

yes, as I mentioned in [link](https://github.com/google/riscv-dv/issues/443#issuecomment-645579443), current fd special values are very hard to hit. I think it may be ok to ignore that for now. I didn't find an efficient way to handle it. We might need to remove that or add plenty direct tests to cover it.

**Comment by yinhanquan** [comment]
ok,thank you for your reply.
