### ISSUE TITLE
Question: is unaligned_load_store test supposed to end after first unaligned load/store? 

### ISSUE THREAD

**Issue by jfranekcodasip** [google/riscv-dv#706]
When running unaligned_load_store_test, the code is generated in such way, that it causes trap after first unaligned L/S instruction and there is no handler for this case so when the trap handler ends, it jumps to test_done label and this is it. 
Since the test has several thousand unused lines, can you please clarify if this is test's wanted behaviour? I would expect the test to continue if the right exception has been set in mcause.

**Comment by udinator** [comment]
Hi @jfranekcodasip - the unaligned_load_store_test should continue running normally after encountering an unaligned L/S instruction, and both Spike/OVPsim should be able to run these as normal.
Are you using one of the latest commits?

**Comment by taoliug** [comment]
The misaligned load/store instruction should be handled by illegal instruction trap handler. Please share the spike log for us to debug further.

**Comment by taoliug** [comment]
Closing this issue for now. Please provide the spike log if you need further help, thanks.
