### ISSUE TITLE
Error 'exception_trap_illegal_instruction' when simulating with SPIKE.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [google/riscv-dv#733]
Background on the issue:

- init_machine_mode wasn't generated in pyflow previously, this was added to simulate asm_tests with RV32F extension. 
- Issue appears randomly while simulating asm_test with floating point instructions. In some cases, the simulation works fine, but fails for some iterations. Spike throws error as illegal instruction & goes in infinite loop while ovpsim doesn't proceed to main.
- Our finding suggest nothing wrong with F instructions but the value loaded into register at first line of init_machine mode: 
```
init_machine_mode:
                  li x24, 0x1800 <-- This
```
 - For failed simulation, replacing immediate value with working immediate value from either SV or pyflow generated asm_test, fixes the issue.

Error Message from SPIKE:
```
core   0: 0xffffffff8000005a (0xf00c0053) fmv.w.x ft0, s8
core   0: exception trap_illegal_instruction, epc 0xffffffff8000005a
core   0:           tval 0x0000000000000000
```

I've attached the needed logs: set of asm file, disassembled log, spike & OVPsim log for both working & erroneous asm files.

**Working Set:**
ASM File:  [working_init_mode_asm_test.log](https://github.com/google/riscv-dv/files/5402872/working_init_mode_asm_test.log)
SPIKE Log: [working_init_mode_spike.log](https://github.com/google/riscv-dv/files/5402876/working_init_mode_spike.log)
OVPSIM Log: [working_init_mode_ovpsim.log](https://github.com/google/riscv-dv/files/5402879/working_init_mode_ovpsim.log)
DISASSEMBLED File:  [working_init_mode_disassembled.log](https://github.com/google/riscv-dv/files/5402882/working_init_mode_disassembled.log)

**Erroneous Set:**
ASM File:  [erroneous_init_mode_asm_test.log](https://github.com/google/riscv-dv/files/5402886/erroneous_init_mode_asm_test.log)
SPIKE Log: [erroneous_init_mode_spike.log](https://github.com/google/riscv-dv/files/5402888/erroneous_init_mode_spike.log)
OVPSIM Log: [erroneous_init_mode_ovpsim.log](https://github.com/google/riscv-dv/files/5402942/erroneous_init_mode_ovpsim.log)
DISASSEMBLED File:  [erroneous_init_mode_disassembled.log](https://github.com/google/riscv-dv/files/5402891/erroneous_init_mode_disassembled.log)

Steps to reproduce:
- Checkout branch floating_test from [here](https://github.com/saurabhsingh-pvips/riscv-dv/tree/floating_test).
- **Run Command:** `python3 run.py --test=riscv_floating_point_arithmetic_test --simulator pyflow --target rv32imfc --iterations 1 
`

I am not sure but maybe you would want to take a look at the core_setting file ([here](https://github.com/saurabhsingh-pvips/riscv-dv/blob/floating_test/pygen/pygen_src/target/rv32imfc/riscv_core_setting.py)) for RV32IMFC, just to be sure it is  as expected. 

Let us know if I can help with anything else from my side.

**NOTE:** This issue is part of [PR#732](https://github.com/google/riscv-dv/pull/732)

**Comment by eroom1966** [comment]
This looks like correct behavior the MSTATUS[FS] bits indicate weather the floating point unit is enabled
If it is not, then executing a floating point instruction will cause a trap

It seems OVP and spike are both (correctly) trapping on the execution of "fmv.w.x ft0, s8" as (FS==0)
Can you describe what you expect to happen ?

Thx
Lee

**Comment by saurabhsingh-pvips** [comment]
Hi Lee,

Thanks for pointing this out. 

The expectation is to be able to simulate FP instructions whenever target rv32imfc is set for the generator.
I looked at my end, the issue appears to come from incorrect implementation of the constraint floating_point_c which makes sure mstatus_fs is 1 if enable_floating_point knob is enabled.

I'll fix that and close the issue. Thanks for the support.
