### ISSUE TITLE
Can‘t print multi-harts info when running spike tool with multi-core settings

### ISSUE THREAD

**Issue by suzhaow** [google/riscv-dv#763]
Execute commands in the riscv-dv directory：
 `python3 run.py --target multi_harts --isa=rv32gc --mabi=lp32d`
But in the log file （in the riscv-dv/spike_sim/）, only core0 program execution information can be found, such as
[riscv_arithmetic_basic_test_0-S.log](https://github.com/google/riscv-dv/files/5730275/riscv_arithmetic_basic_test_0-S.log)
[riscv_arithmetic_basic_test.0.log](https://github.com/google/riscv-dv/files/5730277/riscv_arithmetic_basic_test.0.log)
Did I miss something?
Thanks.

**Comment by taoliug** [comment]
Currently the flow only supports generating program that can be run on multiple harts. It doesn't support run ISS with multi-harts configuration. You will need to invoke ISS manually with different hart configurations.
