### ISSUE TITLE
How to install the riscv-gcc tool chain

### ISSUE THREAD

**Issue by munish37** [google/riscv-dv#90]
I am trying to install riscv-gcc tool chain  by following below commands
1.git clone --recursive https://github.com/riscv/riscv-gnu-toolchain
2.sudo yum install autoconf automake libmpc-devel mpfr-devel gmp-devel gawk  bison flex texinfo patchutils gcc gcc-c++ zlib-devel expat-devel
3../configure --prefix=/opt/riscv
4. make linux

While following these above steps and after running step 4.i am getting compilation error
cc1: internal compiler error: Aborted.
Can you please tell correct steps for installing riscv-gcc toolchain
Can you also please tell after above toolchain installatiom. what should be the value of env variable RISCV_GCC.

Regards
Munish

**Comment by taoliug** [comment]
Hi Munish,

Can you report the toolchain installation issue to the riscv-gnu-toolchain repo? I don't see any obvious issue from the steps you described. Maybe you need to provide more error info for them to debug.
RISCV_GCC should be set to something like  <your_riscv_gcc_path>/bin/riscv64-unknown-linux-gnu-gcc (or bin/riscv32-unknown-linux-gnu-gcc)
